import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Theme } from "@radix-ui/themes";
import { Toaster } from "react-hot-toast";
import Footer from "./components/dashboard/Footer";
import HeaderDashboard from "./components/dashboard/Header";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Doctor Appointment",
  icons: {
    icon: "/favicon.ico",
  },
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  const isUser = session?.user?.role === "user";

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased px-16`}
      >
        {isUser ? (
          <div>
            <HeaderDashboard />
            {children}
            <Footer />
          </div>
        ) : (
          <Theme>
            {children}
            <Toaster />
          </Theme>
        )}
      </body>
    </html>
  );
}
