import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Theme } from "@radix-ui/themes";
import { Toaster } from "react-hot-toast";
import Header from "./components/dashboard/Header";
import Footer from "./components/dashboard/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Doctor Appointment",
  icons: {
    icon: "/favicon.ico",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased px-16`}
      >
        <div>
          <Header />
        </div>
        <Theme>
          {children}
          <Toaster />
        </Theme>
        <div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
